' diagram for IKEv2 CREATE_CHILD_SA (Rekey Child SA)
'
' Mathias Weidner, 2018

@startuml

hide footbox

participant "Initiator" as I
participant "Responder" as R

I -> R: HDR,SK{N(REKEY_SA),SA,Ni,[KEi,]TSi,TSr}
R -> I: HDR,SK{SA,Nr,[KEr,]TSi,TSr}

@enduml
