' simple diagram for IKEv2 IKE_SA_INIT
'
' Mathias Weidner, 2018

@startuml

hide footbox

participant "Initiator" as I
participant "Responder" as R

I -> R: HDR,SAi1,KEi,Ni
R -> I: HDR,SAr1,KEr,Nr[,CertReq]

@enduml
